### ISSUE TITLE
Conflict Between Search Pane and Explorer Pane with "explorer.autoReveal" = true

### ISSUE THREAD

**Issue by infinisuite** [patrys/vscode-code-outline#105] opened 2018-04-10 19:06 UTC
When performing global searches the default behavior is for the 'Search' pane to remain open when clicking inside an editor. However, performing a global search and then clicking inside an editor with this extension enabled results in the workbench automatically switching to the Explorer pane. This is cumbersome if you really just want to click on each search result row and then edit the associated code in the editor. With the current behavior you have to constantly keep clicking back to the Search pane after editing.

The desired behavior (IMHO) would be for the ext to not switch panes.

Also, the default setting for "explorer.autoReveal" is "true" which likely affects this behavior.

Awesome extension!

**Comment by krasoffski** [comment] 2018-04-14 09:11
Confirm this issue is present from release
```
1.22
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
```

**Comment by patrys** [comment] 2018-04-19 10:42
I think this is another duplicate of #103

**Closed by patrys** 2018-04-19 10:42 UTC
Labels: bug
