### ISSUE TITLE
`Cannot read property 'toLowerCase' of undefined` error when viewing templated HTML file

### ISSUE THREAD

**Issue by mihaip** [patrys/vscode-code-outline#25] opened 2017-07-06 20:21 UTC
When loading a .html file with some custom template directives, a "`Cannot read property 'toLowerCase' of undefined" error message appears. The stack in the VSCode dev tools is:

```
Cannot read property 'toLowerCase' of undefined: TypeError: Cannot read property 'toLowerCase' of undefined
    at SymbolNode.compareSymbols (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:42:26)
    at Array.sort (native)
    at SymbolNode.sort (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:48:23)
    at SymbolOutlineProvider.<anonymous> (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:101:22)
    at Generator.next (<anonymous>)
    at fulfilled (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The minimal repro for this is this HTML file:

```
<% import foo %>

<html>
</html>
```

**Comment by piyushkmr** [comment] 2017-09-12 11:47
I am facing the same issue in vscode

**Comment by patrys** [comment] 2017-09-12 12:36
It would help if you could provide a minimal (ie. ideally a couple lines long) example file to reproduce this.

**Comment by mihaip** [comment] 2017-09-12 16:31
@patrys: I did, see "The minimal repro for this is this HTML file" in my initial comment.

**Comment by patrys** [comment] 2017-09-14 11:22
@mihaip I am unable to reproduce this. Are you using any extensions that handle HTML files in a non-standard way? With the built-in HTML syntax I get an empty node for every `<% foo %>` (which matches the Symbol Provider's behavior) but no exception.

**Comment by patrys** [comment] 2017-10-03 18:27
I'm going to close this since I can't reproduce this problem.

**Closed by patrys** 2017-10-03 18:27 UTC
Labels: bug
